/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Controle;

import DAO.FuncionarioDAO;
import DAO.MesaDAO;
import DAO.PedidoPratoDAO;
import DAO.TransactionManager;
import Modelo.Bebida;
import Modelo.Funcionario;
import Modelo.Mesa;
import Modelo.PedidoPrato;
import Modelo.Prato;
import Utils.Data;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Juliana
 */
public class JDialogCadPedidoPrato extends javax.swing.JDialog {

    /**
     * Creates new form JDialogCadPedidoPrato
     */
    private PedidoPrato pedido;
    private DefaultTableModel modelPratos;
    private DefaultComboBoxModel modelCombo;
    private List<Prato> listaPratos;
    private FuncionarioDAO daoFunc;
    private MesaDAO daoMesa;
    private PedidoPratoDAO dao;

    private void criaTabelas() {
        modelPratos = new DefaultTableModel(new String[]{"Nome", "Preço"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTablePratos.setModel(modelPratos);
    }

    private void preenchetabelaPrato() {
        modelPratos.setNumRows(0);
        try {
            List<Prato> lista = this.listaPratos;
            for (Prato p : lista) {
                modelPratos.addRow(new Object[]{p.getNome(),
                    p.getPreco() + ""});

            }
            jTablePratos.updateUI();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void preencheComboBoxFuncionario() {
        daoFunc = new FuncionarioDAO();
        List<Funcionario> funcionarios = daoFunc.lista();
        String[] nomeFunc = new String[funcionarios.size()];
        for (int i = 0; i < funcionarios.size(); i++) {
            nomeFunc[i] = funcionarios.get(i).getCodFuncionario() + " - " + funcionarios.get(i).getNome();
        }
        modelCombo = new DefaultComboBoxModel(nomeFunc);
        jComboBoxGarcon.setModel(modelCombo);
        jComboBoxGarcon.updateUI();
    }

    public void preencheComboBoxMesa() {
        daoMesa = new MesaDAO();
        List<Mesa> mesas = daoMesa.buscaMesaOcupada();
        List<String> mesasOcupadas = new ArrayList<String>();
        for (Mesa mesa : mesas) {
            mesasOcupadas.add("Mesa - " + mesa.getId());
        }
        modelCombo = new DefaultComboBoxModel(mesasOcupadas.toArray());
        jComboBoxMesa.setModel(modelCombo);
        jComboBoxMesa.updateUI();
    }

    private void getPrato() {

        new JDialogConPratos(null, true, true).setVisible(true);
        Prato p = (Prato) Data.hash.remove("prato");
        if (p == null) {
            return;
        }
        listaPratos.add(p);
        preenchetabelaPrato();

    }

    private void deletePrato() {
        int linha = jTablePratos.getSelectedRow();
        listaPratos.remove(linha);
        preenchetabelaPrato();
    }

    public JDialogCadPedidoPrato(java.awt.Frame parent, boolean modal, PedidoPrato pedido) {
        super(parent, modal);
        initComponents();
        this.pedido = pedido;
        criaTabelas();
        this.listaPratos = new ArrayList<Prato>();
        preencheComboBoxFuncionario();
        preencheComboBoxMesa();
        if (pedido != null) {
            jComboBoxGarcon.setSelectedItem(pedido.getIdFuncionario().getCodFuncionario() + " - " + pedido.getIdFuncionario().getNome());
            jComboBoxMesa.setSelectedItem("Mesa - " + pedido.getIdMesa().getId());
            this.listaPratos = pedido.getPratos();
            preenchetabelaPrato();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelMesa = new javax.swing.JLabel();
        jComboBoxGarcon = new javax.swing.JComboBox();
        jLabelGarcon = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePratos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButtonAddPrato = new javax.swing.JButton();
        jButtonRemovePrato = new javax.swing.JButton();
        jComboBoxMesa = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cadastro de Pedidos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMesa.setText("Número da Mesa:");
        jPanel3.add(jLabelMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jPanel3.add(jComboBoxGarcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 270, -1));

        jLabelGarcon.setText("Garçon:");
        jPanel3.add(jLabelGarcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTablePratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablePratos);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 320, 110));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pratos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAddPrato.setText("add");
        jButtonAddPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPratoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonAddPrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, -1, -1));

        jButtonRemovePrato.setText("remove");
        jButtonRemovePrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovePratoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonRemovePrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 370, 220));

        jComboBoxMesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBoxMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 270, -1));

        jButton1.setText("Nova Mesa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 410, 360));

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/zoom.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/limpar.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fechar.jpg"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 460, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private PedidoPrato getDadosDosCampos() {
        PedidoPrato ped = new PedidoPrato();
        if (this.pedido != null) {
            ped=this.pedido;
        }
        ped.setIdMesa(daoMesa.get(Integer.parseInt(jComboBoxMesa.getSelectedItem().toString().substring(jComboBoxMesa.getSelectedItem().toString().lastIndexOf(" ") + 1, jComboBoxMesa.getSelectedItem().toString().length()))));
        ped.setIdFuncionario(daoFunc.get(Integer.parseInt(jComboBoxGarcon.getSelectedItem().toString().substring(0, jComboBoxGarcon.getSelectedItem().toString().indexOf(" ")))));
        ped.setPratos(this.listaPratos);
        

        return ped;
    }

    private void limpaFormularioTodo() {
        jComboBoxMesa.setSelectedIndex(0);
        jComboBoxGarcon.setSelectedIndex(0);
        listaPratos.removeAll(listaPratos);
        preenchetabelaPrato();
    }

    private PedidoPrato inserePedido(PedidoPrato pedido) {
        dao = new PedidoPratoDAO();
        try {
            TransactionManager.beginTransaction();
            pedido = dao.persisteObjeto(pedido);
            TransactionManager.comitTransaction();
            JOptionPane.showMessageDialog(null, "Pedido cadastrado com sucesso");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao inserir Pedido!");
            System.out.println(ex.toString());
        }
        return pedido;
    }

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        JDialog dialog = new JDialogConPedidoPrato(null, true);
        dialog.setLocation(getX() + 50, getY() + 50);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        this.limpaFormularioTodo();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        String aux = validaCampos();
        if ("".equals(aux)) {
            dispose();
            JDialog dialog = new JDialogViewPedidoPrato(null, true, inserePedido(this.getDadosDosCampos()));
            dialog.setLocation(getX() + 50, getY() + 50);
            dialog.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, aux);
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonAddPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPratoActionPerformed
        // TODO add your handling code here:
        getPrato();
    }//GEN-LAST:event_jButtonAddPratoActionPerformed

    private void jButtonRemovePratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePratoActionPerformed
        // TODO add your handling code here:
        deletePrato();
    }//GEN-LAST:event_jButtonRemovePratoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new JDialogCadMesa(null, true, null).setVisible(true);
        preencheComboBoxMesa();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCadPedidoPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCadPedidoPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCadPedidoPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCadPedidoPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCadPedidoPrato dialog = new JDialogCadPedidoPrato(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddPrato;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRemovePrato;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxGarcon;
    private javax.swing.JComboBox jComboBoxMesa;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelGarcon;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTablePratos;
    // End of variables declaration//GEN-END:variables

    private String validaCampos() {
        StringBuilder aux = new StringBuilder();
        aux.append("");
        if (jComboBoxGarcon.getSelectedItem() == null) {
            aux.append("É preciso ter ao menos um funcionario cadastrado!\n");
            jComboBoxGarcon.setBackground(Color.red);
        }
        if (jComboBoxMesa.getSelectedItem() == null) {
            aux.append("É preciso ter ao menos uma mesa cadastrada!\n");
            jComboBoxMesa.setBackground(Color.red);
        }
        if (jTablePratos.getRowCount() == 0) {
            aux.append("É preciso ter ao menos um prato selecionado!\n");
            jTablePratos.setBackground(Color.red);
        }

        return aux.toString();
    }
}
