/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Controle;

import DAO.FuncionarioDAO;
import DAO.MesaDAO;
import Modelo.Bebida;
import Modelo.Funcionario;
import Modelo.Mesa;
import Modelo.Pedido;
import Modelo.Prato;
import Utils.Data;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ligue01
 */
public class JDialogCadPedidos extends javax.swing.JDialog {

    /**
     * Creates new form JDialogCadPedidos
     */
    private DefaultTableModel modelBebidas; 
    private DefaultTableModel modelPratos; 
    private DefaultComboBoxModel modelCombo;
    private List<Bebida> listaBebidas;
    private List<Prato> listaPratos;
    FuncionarioDAO daoFunc;
    MesaDAO daoMesa;
    
    private void criaTabelas() {
        modelBebidas = new DefaultTableModel(new String[]{"Nome","Preço"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        modelPratos = new DefaultTableModel(new String[]{"Nome","Preço"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        jTableBebidas.setModel(modelBebidas);
        jTablePratos.setModel(modelPratos);
    }
    
    private void preenchetabelaBebida() {
        modelBebidas.setNumRows(0);
        try {
            List<Bebida> lista = this.listaBebidas ;
            for (Bebida b : lista) {
                modelBebidas.addRow(new Object[]{b.getNome(),
                    b.getPreco()+""});

            }
            jTableBebidas.updateUI();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    private void preenchetabelaPrato() {
        modelPratos.setNumRows(0);
        try {
            List<Prato> lista2 = this.listaPratos ;
            for (Prato p : lista2) {
                modelBebidas.addRow(new Object[]{p.getNome(),
                    p.getPreco()+""});

            }
            jTablePratos.updateUI();
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public void preencheComboBoxFuncionario(){
        daoFunc=new FuncionarioDAO();
        List<Funcionario> funcionarios=daoFunc.lista();
        String[] nomeFunc=new String[funcionarios.size()];
        for(int i=0;i<funcionarios.size();i++){
            nomeFunc[i]=funcionarios.get(i).getCodFuncionario()+" - "+funcionarios.get(i).getNome();
        }
        modelCombo= new DefaultComboBoxModel(nomeFunc);
        jComboBoxGarcon.setModel(modelCombo);
        jComboBoxGarcon.updateUI();
    }
    
    public void preencheComboBoxMesa(){
        daoMesa=new MesaDAO();
        List<Mesa> mesas=daoMesa.lista();
        String[] lista=new String[mesas.size()];
        for(int i=0;i<mesas.size();i++){
            lista[i]="Mesa - "+mesas.get(i).getId();
        }
        modelCombo= new DefaultComboBoxModel(lista);
        jComboBoxMesa.setModel(modelCombo);
        jComboBoxMesa.updateUI();
    }
    
    private void getPrato() {
        
        new JDialogConComidas(null, true).setVisible(true);
        Prato p = (Prato) Data.hash.remove("prato");
        if (p == null) {
            return;
        }
        listaPratos.add(p);
        preenchetabelaPrato();
        
    }
    
    private void getBebida() {
        
        new JDialogConComidas(null, true).setVisible(true);
        Bebida b = (Bebida) Data.hash.remove("bebida");
        if (b == null) {
            return;
        }
        listaBebidas.add(b);
        preenchetabelaBebida();
        
    }
    
    private void deletePrato(){
        int linha = jTablePratos.getSelectedRow();
        listaPratos.remove(linha);
        preenchetabelaPrato();
    }
    
    private void deleteBebida(){
        int linha = jTableBebidas.getSelectedRow();
        listaBebidas.remove(linha);
        preenchetabelaBebida();
    }
    
    public JDialogCadPedidos(java.awt.Frame parent, boolean modal, Pedido pedido) {
       super(parent, modal);
        initComponents();
        criaTabelas();
        preencheComboBoxFuncionario();
        preencheComboBoxMesa();
        if(pedido!=null){
//            jTextFieldMesa.setText(pedido.getIdMesa()+"");
//            jComboBoxGarcon.setSelectedItem(pedido.getIdFuncionario());
//            jListPrato.getSelectedValuesList();
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabelMesa = new javax.swing.JLabel();
        jComboBoxGarcon = new javax.swing.JComboBox();
        jLabelGarcon = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBebidas = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTablePratos = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jButtonAddBebida = new javax.swing.JButton();
        jButtonRemoveBebida = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButtonAddPrato = new javax.swing.JButton();
        jButtonRemovePrato = new javax.swing.JButton();
        jComboBoxMesa = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButtonPesquisar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButtonLimpar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Cadastro de Pedidos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelMesa.setText("Número da Mesa:");
        jPanel3.add(jLabelMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, 20));

        jPanel3.add(jComboBoxGarcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 270, -1));

        jLabelGarcon.setText("Garçon:");
        jPanel3.add(jLabelGarcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jTableBebidas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTableBebidas);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 160, 110));

        jTablePratos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTablePratos);

        jPanel3.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 150, 110));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Bebidas", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAddBebida.setText("add");
        jButtonAddBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBebidaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAddBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 163, -1, -1));

        jButtonRemoveBebida.setText("remove");
        jButtonRemoveBebida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemoveBebidaActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonRemoveBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 163, -1, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, 190, 220));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pratos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAddPrato.setText("add");
        jButtonAddPrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddPratoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonAddPrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 165, -1, -1));

        jButtonRemovePrato.setText("remove");
        jButtonRemovePrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRemovePratoActionPerformed(evt);
            }
        });
        jPanel4.add(jButtonRemovePrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(105, 165, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 190, 220));

        jComboBoxMesa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel3.add(jComboBoxMesa, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 270, -1));

        jButton1.setText("Nova Mesa");
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 410, 360));

        jButtonPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/zoom.png"))); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 130, -1));

        jPanel2.setBackground(new java.awt.Color(102, 102, 102));

        jButtonLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/limpar.png"))); // NOI18N
        jButtonLimpar.setText("Limpar");
        jButtonLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/salvar.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/fechar.jpg"))); // NOI18N
        jButtonFechar.setText("Fechar");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonFechar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 460, 80));

        pack();
    }// </editor-fold>//GEN-END:initComponents

     private Pedido getDadosDosCampos() {
        Pedido pedido = new Pedido();
//        pedido.setIdMesa(jTextFieldMesa.getText());
//        pedido.setIdFuncionario(jComboBoxGarcon.getSelectedItem().toString());
//        pedido.setPratos((jListPrato.getSelectedValue().toString()));
//        pedido.setPratos(jListPrato.getSelectedValuesList());

        return pedido;
    }
    
    private void limpaFormularioTodo() {
//        jTextFieldMesa.setText("");
//        jComboBoxGarcon.setSelectedIndex(0);
//        jListPrato.setSelectedIndex(0);

    }
    
    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        JDialog dialog = new JDialogConComidas(null, true);
        dialog.setLocation(getX() + 50, getY() + 50);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparActionPerformed
        this.limpaFormularioTodo();
    }//GEN-LAST:event_jButtonLimparActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        dispose();
        JDialog dialog = new JDialogViewPedido(null, true, this.getDadosDosCampos());
        dialog.setLocation(getX() + 50, getY() + 50);
        dialog.setVisible(true);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jButtonAddPratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddPratoActionPerformed
        // TODO add your handling code here:
        getPrato();
    }//GEN-LAST:event_jButtonAddPratoActionPerformed

    private void jButtonAddBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBebidaActionPerformed
        // TODO add your handling code here:
        getBebida();
    }//GEN-LAST:event_jButtonAddBebidaActionPerformed

    private void jButtonRemovePratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemovePratoActionPerformed
        // TODO add your handling code here:
        deletePrato();
    }//GEN-LAST:event_jButtonRemovePratoActionPerformed

    private void jButtonRemoveBebidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveBebidaActionPerformed
        // TODO add your handling code here:
        deleteBebida();
    }//GEN-LAST:event_jButtonRemoveBebidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogCadPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogCadPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogCadPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogCadPedidos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogCadPedidos dialog = new JDialogCadPedidos(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddBebida;
    private javax.swing.JButton jButtonAddPrato;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLimpar;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonRemoveBebida;
    private javax.swing.JButton jButtonRemovePrato;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox jComboBoxGarcon;
    private javax.swing.JComboBox jComboBoxMesa;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelGarcon;
    private javax.swing.JLabel jLabelMesa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableBebidas;
    private javax.swing.JTable jTablePratos;
    // End of variables declaration//GEN-END:variables
}
